# Generated by Django 3.1 on 2020-09-23 01:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200913_1141'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='about',
            name='subtitulo',
        ),
    ]
