# Generated by Django 3.1 on 2020-09-23 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_about_subtitulo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='about',
            name='descripcion2',
        ),
        migrations.AddField(
            model_name='about',
            name='historia',
            field=models.TextField(blank=True, verbose_name='historia'),
        ),
        migrations.AddField(
            model_name='about',
            name='mision',
            field=models.TextField(blank=True, verbose_name='mision'),
        ),
        migrations.AddField(
            model_name='about',
            name='vision',
            field=models.TextField(blank=True, verbose_name='vision'),
        ),
    ]
