# Generated by Django 3.1 on 2020-09-23 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_servicio_portada'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='portada',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
